### ISSUE TITLE
Question about ReverseRoom training

### ISSUE THREAD

**Issue by ppk03** [ch1nghz/NTbuster#1]
Hi, I'm very interested in ReverseRoom's Windows Kernel Vulnerability course and Browser Vulnerability course, the topics they discuss seem to be very advanced. Although I saw that it is only sold to companies, I am still curious if I can bring a few more people to the course, can it be sold to individuals? Also, what is the price of the course? Are the courses supported online?

**Comment by ch1nghz** [comment]
Hi there, 
we regret to inform you that our training and services are currently suspended. Our team is currently focused on the development of the open source edition of Vulecc.
